services:
  db:
    image: mariadb:10.11.13
    container_name: edsa_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_DATABASE:-db_edsa}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      # Port 3306 host hanya akan "listen" di 127.0.0.1
      - "127.0.0.1:3306:3306"
    volumes:
      - db_edsa:/var/lib/mysql
    networks:
      - edsa
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  edsa:
volumes:
  db_edsa: