services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - user=${APP_USER}
        - uid=${APP_UID}
    container_name: edsa_laravel
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/var/www/
    networks:
      - edsa
  dash:
    image: nginx:1.28.0-alpine
    container_name: edsa_dashboard
    restart: unless-stopped
    volumes:
      - ./:/var/www/
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - edsa
    ports:
      - "80:80"
    depends_on:
      - app
networks:
  edsa:
    driver: bridge